Add wallet_rpc spec for wallet<>dapp communication
starkware-libs/starknet-specs pull request #203
Opened 2024-03-28 13:21 UTC by amanusk

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-specs/203)

2024-03-31 07:02 UTC, amanusk reviewed
Please review the current PR in general, hope it covers all, but could have some things missing/inaccurate
Please ACK the comments you are tagged in, we discussed this in the call, but the changes are not yet reflected

2024-03-31 07:02 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "type": "object",
Do we want to add `class_hash` (in addition to `compiled_class_hash` or was it intentionally left out?

@dhruvkelawala @avimak @PhilippeR26 @tabaktoni @ArielElp @naorye
@stanleyyconsensys

2024-03-31 07:08 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "USER_REFUSED": {
Any additional errors we should return?

@dhruvkelawala @avimak @PhilippeR26 @tabaktoni @ArielElp @naorye
@stanleyyconsensys

2024-04-02 08:30 UTC, vladutjs commented on wallet-api/wallet_rpc.json
> +      "name": "starknet_signTypedData",
should we rename this to `wallet_signTypedData` as well?

2024-04-02 11:14 UTC, stanleyyconsensys commented on wallet-api/wallet_rpc.json
> +      "USER_REFUSED": {
@amanusk , for metamask, there will be a install process, user can refuse to install, i dont have any suggestion on that error code, as it is quite unique for metamask, and there may be some more metamask "SNAP" error case

2024-04-02 11:17 UTC, stanleyyconsensys commented on wallet-api/wallet_rpc.json
> +          "name": "silent_mode",
@amanusk , as i mentioned, for Metamask SNAP, there is no way to control the wallet-unlock UI from SNAP, hence, we may ignore that parameter

2024-04-02 15:44 UTC, PhilippeR26 commented on wallet-api/wallet_rpc.json
> +      "summary": "Deploy a new account in the current network. It's not linked to the type of accounts provided by the wallet ; you have to define which class to use",
Should be indicated that no pre-fund is necessary ; the current account of the wallet will pay the fees to deploy the new account.

2024-04-03 11:30 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/schemas/STARKNET_CHAIN_ID"
Agree, it should be flexible

2024-04-03 12:35 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +          "name": "silent_mode",
That param should be optional. According to the Wallet SNIP api, it's optional anyways

2024-04-03 12:36 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/schemas/STARKNET_CHAIN_ID"
But then we need to decide if it will be of type "SN_MAIN" or `encode.shortString("SN_MAIN")` (Hex-string)

2024-04-03 12:56 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +        "summary": "If wallet agrees to change network, return true. If the current network is selected, return true. If network is inconsistent, return false",
What do you mean by inconsistent network?

2024-04-03 12:56 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +      "name": "starknet_addInvokeTransaction",
i think `starknet_addInvokeTransaction` make more sense as it's an interaction with starknet and not a wallet function

2024-04-03 12:56 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +      "name": "starknet_addDeclareTransaction",
Same as above

2024-04-03 12:56 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/errors/UNEXPECTED_ERROR"
Yes, I agree to @PhilippeR26 point

2024-04-03 12:56 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +      "name": "starknet_signTypedData",
Here we can use `wallet_signTypedData` because wallet is doing it and no interaction with starknet itself is involved

2024-04-03 13:15 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "name": "starknet_addInvokeTransaction",
Reasoning for the proposed change is to differenciate it from the node rpc `starknet_addInvokeTransaction`, which has a different structure

2024-04-03 13:22 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/schemas/STARKNET_CHAIN_ID"
@dhruvkelawala the issue is what to return if we previously added a custom chain_id, and then request a chain_id that is not in the enum
It can also set it to be `AnyOf` CHAIN_ID or STARKNET_CHAIN_ID

2024-04-03 13:23 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "summary": "If wallet agrees to change network, return true. If the current network is selected, return true. If network is inconsistent, return false",
Something in the network configuration format is incorrect. Happy to fix to a better summary :)

2024-04-03 13:24 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "name": "wallet_requestAccounts",
Thanks looks like there is a duplicate. I'll remove

2024-04-04 08:59 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/errors/INCORRECT_NETWORK"
I'll change the description to only return true if user agreed and network added succesfuly

2024-04-04 09:15 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "$ref": "./api/starknet_api_openrpc.json#/components/schemas/CONTRACT_CLASS"
Can you please explain the difference? abi is also a string in the node rpc spec

2024-04-04 09:18 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "USER_REFUSED": {
@stanleyyconsensys I think user refused or unexpected error can be enough to cover this case. We might want to add other errors in the future

2024-04-04 12:45 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +          "required": []
When the user declines/denies/exit-window, it should return an empty array?

2024-04-04 12:48 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +          "type": "array",
The same is on the ETH but I don't understand why it is an array when the user can have only one active account address at the time?

2024-04-04 12:54 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      "summary": "Opens a window in the wallet and ask the authorization to connect your DAPP",
the description is misleading;
this message does not request for any permissions, it only returns the list of **existing** permissions (the equivalent for "isConnected")

2024-04-04 12:55 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "required": []
it returns a list of existing permissions; no permissions -> empty array

2024-04-04 12:58 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "summary": "if true, the wallet will not show the wallet-unlock UI in case of a locked wallet, nor the dApp-approve UI in case of a non-allowed dApp",
the `, nor the dApp-approve UI in case of a non-allowed dApp` is misleading; this is how a dapp requests/receives the `accounts` permission

2024-04-04 13:01 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/schemas/STARKNET_CHAIN_ID"
imo an hex-string should be fine 👍

2024-04-04 13:04 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "properties": {
this object is missing a tx-version parameter which is crucial for the `sigdata` part ofc.

2024-04-04 13:07 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      "summary": "Request from the current wallet the data required to deploy the account at the current address",
this will show a permission-request popup on Braavos

2024-04-04 13:11 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "summary": "If wallet agrees to change network, return true. If the current network is selected, return true. If network is inconsistent, return false",
and if the user rejects the request throw an exception?

2024-04-04 13:16 UTC, dhruvkelawala commented on wallet-api/wallet_rpc.json
> +        "type": "object",
We can get `class_hash` from contract class but we can have it as optional field

2024-04-04 13:17 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "summary": "If adding a token is agreed, return true",
perhaps it would be clearer to explicitly mention that the wallet will display the approval UI here.

2024-04-04 13:31 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      "summary": "Add a new network in the list of networks of the wallet",
Perhaps it would be clearer to explicitly mention that the wallet will display the approval UI here

2024-04-04 13:32 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "name": "Starknet Chain Id to add",
```suggestion
          "name": "Starknet Chain to add",
```

2024-04-04 13:36 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "description": "The information needed to invoke the function (or account, for version 1 transactions)",
not sure if I understand the `or account, for version 1 transactions` part

2024-04-04 13:40 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "message": "An unexpected error occurred",
pls define "unexpected", and could we generalize it like "An error occurred" (UNKNOWN_ERROR) and then use it for all non-contextualized errors?

2024-04-04 13:44 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "$ref": "#/components/errors/UNEXPECTED_ERROR"
The dApp could find it on the chain by itself; forwarding specific errors will open the door to a deep rabbithole :)

2024-04-04 13:47 UTC, avimak commented on wallet-api/wallet_rpc.json
> +            "description": "primaryType represents the top-level type of the object in the message",
typo?

2024-04-04 13:47 UTC, avimak commented on wallet-api/wallet_rpc.json
> +            "description": "primaryType represents the top-level type of the object in the message",
(e.g. this is `types`)

2024-04-04 13:47 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +          "description": "The information needed to invoke the function (or account, for version 1 transactions)",
My bad, irrelevant

2024-04-04 13:50 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "$ref": "#/components/schemas/FELT"
padded? non-padded? let's be explicit

2024-04-04 13:54 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "description": "Details of an onchain Starknet token",
```suggestion
        "description": "Details of an onchain Starknet ERC20 token",
```

2024-04-04 13:56 UTC, avimak commented on wallet-api/wallet_rpc.json
> +            "$ref": "#/components/schemas/FELT"
could be both selector hex or name, e.g. "approve" or "0x1234.."

2024-04-04 13:56 UTC, avimak commented on wallet-api/wallet_rpc.json
> +            "$ref": "#/components/schemas/FELT"
so perhaps it worth being explicit here

2024-04-04 13:58 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      "DEPLOY_ACCOUNT_TXN": {
I guess we should remove it

2024-04-04 14:00 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "chainId": {
this object uses camelCase while the other use snake_case

2024-04-04 14:02 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      "USER_REFUSED": {
pls mark "non generic" errors as optional

2024-04-04 14:02 UTC, avimak commented on wallet-api/wallet_rpc.json
> +      },
could be generalized under a single "Invalid request" error which could also cover for other messages like add_invoke/add_declare ..

2024-04-08 00:57 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "summary": "Request from the current wallet the data required to deploy the account at the current address",
Thanks, we should also have options to returns errors here

2024-04-08 00:58 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "summary": "If wallet agrees to change network, return true. If the current network is selected, return true. If network is inconsistent, return false",
indeed

2024-04-08 01:09 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +          "version": {
@avimak Is this not the version you refer to in your comment?
How can tx-version affect account deployment address?

2024-04-08 01:13 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +            "$ref": "#/components/schemas/FELT"
Do we really want to allow both? 
What if someone has an abi with both a hex string and the hash of that hex string

2024-04-08 01:58 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "type": "object",
Added

2024-04-08 05:37 UTC, avimak commented on wallet-api/wallet_rpc.json
> +        "$ref": "#/components/schemas/FELT"
I don't think there is a widely agreed practice.

2024-04-08 05:42 UTC, avimak commented on wallet-api/wallet_rpc.json
> +            "$ref": "#/components/schemas/FELT"
not sure if it's a valid ABI then; probably worth checking with @ArielElp. anyway, we could decide it's a named selector and not its hash, but let's be explicit either way.

2024-04-08 05:43 UTC, avimak commented on wallet-api/wallet_rpc.json
> +          "version": {
not account `address` but the payload's `sigdata` structure.

2024-04-09 10:35 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +            "$ref": "#/components/schemas/FELT"
Following discussion, changed this to "string" for named selector

2024-04-09 10:37 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +        "$ref": "#/components/schemas/FELT"
Added a padded felt type

2024-04-14 08:09 UTC, ArielElp commented on wallet-api/wallet_rpc.json
> +                  "$ref": "#/components/schemas/PERMISSION"
permission is an enum with "account" being the only option, is this supposed to be an accounts array?

2024-04-14 08:09 UTC, ArielElp commented on wallet-api/wallet_rpc.json
> +      "name": "wallet_addInvokeTransaction",
Maybe we should rename this to not confuse with the starknet RPC? e.g. wallet_multicall

2024-04-14 08:09 UTC, ArielElp commented on wallet-api/wallet_rpc.json
> +        "required": ["contract_address", "entry_point"]
why not required calldata? it can be empty

2024-04-14 08:09 UTC, ArielElp commented on wallet-api/wallet_rpc.json
> +      "name": "wallet_addDeclareTransaction",
consider renaming to wallet_declare

2024-04-15 11:38 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +      "name": "wallet_addInvokeTransaction",
that's why we changed it to be prefixed with `wallet_`

2024-04-15 18:48 UTC, tabaktoni requested changes

2024-04-15 18:48 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +        "message": "An error occured (INVALID_REQUEST_PAYLOAD)"
```suggestion
        "message": "An error occurred (INVALID_REQUEST_PAYLOAD)"
```

2024-04-15 18:48 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +        "message": "An error occured (NOT_ERC20)"
```suggestion
        "message": "An error occurred (NOT_ERC20)"
```

2024-04-17 08:10 UTC, penovicp commented on wallet-api/wallet_rpc.json
> +        "properties": {
The `revision` property which was defined in [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#domain-separator) should be added.

2024-04-17 08:10 UTC, penovicp commented on wallet-api/wallet_rpc.json
> +            {
Similar to the `StarknetMerkleType`, `StarknetType` should also reference an [enum type](https://github.com/starknet-io/starknet.js/blob/v6.6.6/src/types/typedData.ts#L29) that was defined in [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-an-enum).

2024-04-17 08:11 UTC, penovicp commented on wallet-api/wallet_rpc.json
> +          },
`types` should be an object with arbitrary keys where each key maps to a `StarknetType` array ([SNIP-12 example](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#json-example)). 

Not sure if this suggestion code is a valid way to define it (I can't find`additionalProperties` on `open-rpc.org` but it can be found on `json-schema.org` and is used in [one other place](https://github.com/starkware-libs/starknet-specs/blob/v0.7.1/api/starknet_api_openrpc.json#L1279) in the spec):
```suggestion
          "types": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/STARKNET_TYPE"
              }
            }
          },
```

2024-04-17 08:11 UTC, penovicp commented on wallet-api/wallet_rpc.json
> +          "primary_type": {
Changing the primary type property from camel case to snake case would mean that it wouldn't align with the [SNIP-12 specification](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md?plain=1#L404).

2024-04-17 12:59 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +          "primary_type": {
Same is for STARKNET_DOMAIN chain_id

2024-04-17 13:22 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +      },
```suggestion
```

2024-04-17 13:22 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +      "SYMBOL": {
I would recommend renaming to TOKEN_SYMBOL to fix collision with js Symbol (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)

```suggestion
      "TOKEN_SYMBOL": {
```

2024-04-17 13:22 UTC, tabaktoni commented on wallet-api/wallet_rpc.json
> +      "TXN_HASH": {
Should we call this padded TX hash to differentiate from api TXN_HASH which is based on FELT ?
If agreed it needs to be renamed on usage lines.

```suggestion
      "PADDED_TXN_HASH": {
```

2024-04-18 14:26 UTC, vladutjs commented on wallet-api/wallet_rpc.json
> +      "summary": "Request from the current wallet the data required to deploy the account at the current address",
@amanusk on AX this is not showing any popup, but only a permissioned dapp can request it.

2024-04-24 02:08 UTC, amanusk commented on wallet-api/wallet_rpc.json
> +          },
Thanks @penovicp! applied this and your suggestions for SNIP 12

2024-05-26 17:06 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/203#-:-NyprPkf9QkKYiJ6jilQ:bnfp4nl)* status: all files reviewed, 52 unresolved discussions (waiting on @amanusk, @avimak, @dan-ziv, @dhruvkelawala, @naorye, @penovicp, @PhilippeR26, @stanleyyconsensys, @tabaktoni, and @vladutjs)



<!-- Sent from Reviewable.io -->

2024-05-26 17:07 UTC, ArielElp reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/203)* status: all files reviewed, 51 unresolved discussions (waiting on @amanusk, @avimak, @dan-ziv, @dhruvkelawala, @naorye, @penovicp, @PhilippeR26, @stanleyyconsensys, @tabaktoni, and @vladutjs)



<!-- Sent from Reviewable.io -->

2024-05-27 11:58 UTC, ArielElp approved these changes
> Dismissed @vladutjs, and @vladutjs from 43 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)



<!-- Sent from Reviewable.io -->

2024-05-27 11:58 UTC, merged