Starknet WS specification proposal
starkware-libs/starknet-specs pull request #211
Opened 2024-06-30 07:59 UTC by amanusk

# How to read this spec

* Each subscription type is described by its own method, with relevant parameters. 
* The result of the subscription is a subscription ID, used to determine which stream a notification was received from, as well as an option to unsubscribe.
* For each subscription type, there is a notification method describing the results received in each streamed event
* A Reorg error is possible on all subscriptions, notifying that a reorg has occurred, and it is up to the client to treat this case according to their business logic

2024-06-30 10:02 UTC, ittaysw requested changes

2024-06-30 10:02 UTC, ittaysw commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribeNewHeads",
in Ethereum there is just one method `eth_subscribe` where the different types and their arguments are in the params.

2024-06-30 13:51 UTC, amanusk commented on api/starknet_ws_api.json
> +            "schema": {
Just to make sure, your suggestions is to create a new component in `starknet_api_openrpc` to be used in both?

2024-06-30 13:55 UTC, amanusk commented on api/starknet_ws_api.json
> +      "BLOCK_SYNCING_STATUS": {
You are right, didn't realize it was already defined. Fixing

2024-06-30 14:01 UTC, amanusk commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribeNewHeads",
We would like to have separate methods for each subscription, as this is partially the reason there is no subscription spec defined for Ethereum 

https://github.com/ethereum/execution-apis/issues/496

2024-07-01 04:57 UTC, ittaysw commented on api/starknet_ws_api.json
> +            "schema": {
Yes

2024-07-01 05:00 UTC, ittaysw commented on api/starknet_ws_api.json
> +          "$ref": "#/components/errors/STARKNET_REORG_DETECTED"
I think another type of subscription.

2024-07-01 10:55 UTC, amanusk commented on api/starknet_ws_api.json
> +            "starting_block_hash": {
Indeed very similar, but there is no use  for `current_block`

@ArielElp WDYT, makes sense to split SYNC_STAUTS, or duplicate?

2024-07-02 05:11 UTC, ittaysw commented on api/starknet_ws_api.json
> +      "name": "starknet_subscriptionSyncing",
What is the use case here? Do we expect nodes to start syncing, then stop, then start again?

2024-07-02 05:24 UTC, ittaysw commented
What is the behavior of these subscriptions when a node is syncing? E.g. I subscribed to events, will i get all events as it is going through blocks? A node may be syncing back as well, what is the meaning of 'latest' then? And if two nodes are syncing on the same range, one forward, one backward, will they send different events on the stream?

Seems to me like we should just not allow subscribing when a node is syncing, only when it is fully synced. Then we can also remove the syncing status call.

2024-07-02 05:25 UTC, ittaysw commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribePendingTransactions",
maybe instead have a 'block' parameter to starknet_subscribeTransactions which will also be more uniform with starknet_subscribeEvents

2024-07-02 05:25 UTC, ittaysw commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribeSyncing",
What is the use case here? Do we expect nodes to start syncing, then stop, then start again?

This can be also the stream for reorg notification

2024-07-04 05:43 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/211)* status: 0 of 7 files reviewed, 16 unresolved discussions (waiting on @amanusk and @ittaysw)

___
*[`api/starknet_ws_api.json` line 325 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#gh-1660116277:-O0wDWiZ7u-XBLa-mPye:b-j2bja6) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/8532695e8b4bbd0ba4d393065a379f8ba8d4a15e/api/starknet_ws_api.json#L325)):*
<details><summary><i>Previously, ittaysw (Ittay Dror) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Why not have the response of tx status subscription be allOf tx_hash and TXN_STAUTS? NEW_TXN_STATUS is weird.
___
*[`api/starknet_ws_api.json` line 380 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#gh-1660119181:-O0wFeeF6k_S-h9pNU0A:bukex8q) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/8532695e8b4bbd0ba4d393065a379f8ba8d4a15e/api/starknet_ws_api.json#L380)):*
<details><summary><i>Previously, amanusk (amanusk) wrote…</i></summary><blockquote>

Indeed very similar, but there is no use  for `current_block`

@ArielElp WDYT, makes sense to split SYNC_STAUTS, or duplicate? 
</blockquote></details>

I think we can keep as-is, but up to you
___
*[`api/starknet_ws_api.json` line 59 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#-O0wECct81L9MR13gnks:-O0wECct81L9MR13gnkt:bsfi71r) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/46e90d1859f7f27e47c3fa77b1b35d33fdb1118e/api/starknet_ws_api.json#L59)):*
> ```JSON
>           "required": false,
>           "schema": {
>             "$ref": "#/components/schemas/FELT"
> ```

ADDRESS
___
*[`api/starknet_ws_api.json` line 63 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#-O0wDvVT9gVQQly6A-Nc:-O0wDvVT9gVQQly6A-Nd:b-anv9j5) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/46e90d1859f7f27e47c3fa77b1b35d33fdb1118e/api/starknet_ws_api.json#L63)):*
> ```JSON
>         },
>         {
>           "name": "keys",
> ```

keys is a nested array, e.g. [[],[1, 2], [3]], means (k1=1 or k1=2) and k3=3, with no constraints on k0
___
*[`api/starknet_ws_api.json` line 105 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#-O0wEOAP96_yyDQO35Jj:-O0wEOAP96_yyDQO35Jk:bn9j0uv) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/46e90d1859f7f27e47c3fa77b1b35d33fdb1118e/api/starknet_ws_api.json#L105)):*
> ```JSON
>           "name": "result",
>           "schema": {
>             "$ref": "./api/starknet_api_openrpc.json#/components/schemas/EMITTED_EVENT"
> ```

am I necessarily getting events one at a time? does an array of EMITTED_EVENT make sense here?
___
*[`api/starknet_ws_api.json` line 200 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#-O0wG7v292DP-yy-RXfc:-O0wG7v292DP-yy-RXfd:bliu7r3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/46e90d1859f7f27e47c3fa77b1b35d33fdb1118e/api/starknet_ws_api.json#L200)):*
> ```JSON
>           "name": "result",
>           "description": "Either a tranasaction hash or full transaction details, based on subscription",
>           "schema": {
> ```

same as my events question, are we insisting on one item or can we can a chunk of results?


<!-- Sent from Reviewable.io -->

2024-07-04 09:56 UTC, kirugan commented on api/starknet_ws_api.json
> +            "$ref": "./api/starknet_api_openrpc.json#/components/schemas/BLOCK_HEADER"
why this is part of `params` field?

2024-07-04 09:58 UTC, kirugan commented on api/starknet_ws_api.json
> +          "$ref": "#/components/errors/STARKNET_REORG_DETECTED"
Do you thinks it's valuable to provide info how deep is reorg? alongside error itself

2024-07-04 10:02 UTC, kirugan commented on api/starknet_ws_api.json
> +        "code": 202,
if we following json-rpc spec (which might be the case because `WEBSOCKET_SUBSCRIPTION_CLOSED` code is in valid range) then we should follow it here as well:
```
-32000 to -32099 	Server error 	Reserved for implementation-defined server-errors.
```

2024-07-04 10:20 UTC, amanusk commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribePendingTransactions",
This should be an interim solution until `PendingTransactions` reflects transactions in the mempool.
I don't think it makes sense to stream all transactions if they are part of an already complete block

2024-07-04 10:24 UTC, amanusk commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribeSyncing",
Worth a discussion in the nodes-collab meeting. It's currently here since Ethereum has such endpoint. 
The usecase I can think of is indeed to only start some process after sync is complete

2024-07-04 11:31 UTC, amanusk commented on api/starknet_ws_api.json
> +            "$ref": "./api/starknet_api_openrpc.json#/components/schemas/BLOCK_HEADER"
This is how Open RPC spec describes notifications, which is the object we want to describe.
This is also the case for how Juno works right now ("result" within "params")
https://juno.nethermind.io/websocket#subscribe-to-newly-created-blocks

2024-07-04 13:18 UTC, ittaysw requested changes

2024-07-04 13:20 UTC, kkovaacs commented on api/starknet_ws_api.json
> +          "name": "subscription_ID",
Can we make these lowercase? I think in other parts of the JSON-RPC specification we're using `_id` and not uppercase.

2024-08-12 07:18 UTC, amanusk commented on api/starknet_ws_api.json
> +      "params": [
Yes, instead of constantly polling for pending block and going over new transactions.
This is a widely used usecase.
Post mempool, the can be reused to stream all txs received by the node's mempool, regardless of inclusion in a block.

We can still consider a `sender_address` filter

2024-08-12 07:59 UTC, amanusk commented on api/starknet_ws_api.json
> +          "name": "subscription_ID",
You are right, updating

2024-08-12 08:01 UTC, amanusk commented on api/starknet_ws_api.json
> +      "name": "starknet_subscribeTransactionStatus",
That's a great point, can we express this in spec somehow? Or just in the description?

2024-08-12 08:26 UTC, amanusk commented on api/starknet_ws_api.json
> +              "description": "The reason why the subscription was closed",
@kkovaacs I took this error from the Pathfinder WS spec :), 
Can you please elaborate on how the "reason" field is used? 
Or is this some standard? 
Thanks

2024-08-12 08:32 UTC, amanusk commented
## Latest changes based on discussions above

- Add `sender_address` filter to pending transactions subscriptions
- Add `subscriptionReorg` that can be received by Headers, Events, Transaction Status
- Remove sync subscription and events
- Nodes only allow WS sucscriptions after they are synced
- Updated keys as in event filter


## Open question:
- Allowing to start a subscription from a previous block and "catch up" to the latest (applies to headers, events, transaction Status)
- Returning subscription notifications one by one or as an array (applies to Headers, Events, Pending Transactions)

These are also questions for Full nodes and how much does this complicate implementation

2024-08-14 15:13 UTC, kkovaacs commented on api/starknet_ws_api.json
> +      ]
I think we should just remove this -- first, `starknet_subscriptionPendingTransaction` is a notification, so no response (or error) is possible.
Also, `WEBSOCKET_SUBSCRIPTION_CLOSED` should be something that is sent by the _node_. We should probably just close the connection instead.

2024-08-14 15:13 UTC, kkovaacs commented on api/starknet_ws_api.json
> +        "description": "True if the unsubscription was successful",
It's probably an internal error in the dapp I think. The only case Pathfinder returns `false` here is when you're specifying a non-existent subscription id. We could also just convert this into an error instead.

2024-08-14 15:13 UTC, kkovaacs commented on api/starknet_ws_api.json
> +      "WEBSOCKET_SUBSCRIPTION_CLOSED": {
As I wrote above, I think this should be removed.

2024-08-14 15:13 UTC, kkovaacs commented on api/starknet_ws_api.json
> +              "description": "The reason why the subscription was closed",
No, this is an oversight / error in the specification. This is not really an error but a notification (or at least it should be). I think we should just remove this altogether.

2024-08-25 15:02 UTC, amanusk commented
Update:
Added the option to subscribe to up to 1024 blocks back, and the accompanying error

2024-08-25 15:02 UTC, amanusk commented on api/starknet_ws_api.json
> +      ]
Thanks ,removing

2024-08-25 15:03 UTC, amanusk commented on api/starknet_ws_api.json
> +      "params": [
Added `sender_address` filter, and an accompanying error for too many addresses

2024-09-19 07:26 UTC, ArielElp commented on api/starknet_ws_api.json
> +          "summary": "The block to get notifications from, default is latest, limited to 1024 blocks back",
I tend to agree that we can leave it up to nodes, I guess the original motivation was to avoid confusion on different rpc providers supporting different things. For now I'm leaving this in so that it can be part of 0.8.0-rc0, we can continue discussing this towards the final release.

2024-09-19 09:50 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 1 of 2 files at r2, 3 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/211#-:-O78B0eb5Djrxg19gf47:bnfp4nl)* status: all files reviewed, 28 unresolved discussions (waiting on @amanusk, @ittaysw, @kirugan, @kkovaacs, and @sistemd)



<!-- Sent from Reviewable.io -->

2024-09-19 09:54 UTC, ArielElp approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/211)* status: all files reviewed, 24 unresolved discussions (waiting on @amanusk, @ittaysw, @kirugan, @kkovaacs, and @sistemd)



<!-- Sent from Reviewable.io -->

2024-09-19 10:00 UTC, ArielElp approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/211)* status: all files reviewed, 23 unresolved discussions (waiting on @amanusk, @ittaysw, @kirugan, @kkovaacs, and @sistemd)



<!-- Sent from Reviewable.io -->

2024-09-19 10:02 UTC, ArielElp approved these changes
> Dismissed @sistemd, and @sistemd from 23 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amanusk)



<!-- Sent from Reviewable.io -->

2024-09-19 10:02 UTC, merged