Add format script and run it
starkware-libs/starknet-specs pull request #241
Opened 2024-11-07 12:53 UTC by amanusk

No more messing around with formatting
Just run `npm run format_all` to make sure all files are on the same format

2024-11-14 06:23 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/241#-:-OBdKqm_B7Yw7D6Wx4Qk:bnfp4nl)* status: 3 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-29 16:12 UTC, FabijanC requested changes

2024-11-29 16:12 UTC, FabijanC commented on format.js
Instead of writing a custom formatter, I would suggest using a tool like `prettier` that can perform the formatting and which can also be used for checking the format in a CI step.

2024-12-05 08:16 UTC, amanusk commented
Superceeded by #258

2024-12-05 08:16 UTC, closed without merging