add estimateFee to the JSON RPC
starkware-libs/starknet-specs pull request #4
Opened 2022-05-29 16:51 UTC by ArielElp

2022-05-30 06:57 UTC, lior-stark requested changes
This should branched off the 0.10.0 version, which has the getClassXXX methods.
please rebase over master.

2022-05-30 06:57 UTC, lior-stark commented on api/starknet_api_openrpc.json
> +            "paramStructure": "by-name",
why do you need to specify this?

2022-05-30 06:57 UTC, lior-stark commented on api/starknet_api_openrpc.json
> +                    "name": "block_hash",
so the state assumed is the state at the beginning or end of the block?

2022-05-31 06:39 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 438 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/4#-N3No2HvW-TM5BJq2TME-r1-438:-N3NoP6v6FEf_86GOiMo:b26iizn) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e6275ae34a94aa5c280eb41d5adf533c11588422/api/starknet_api_openrpc.json#L438)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why do you need to specify this?
</blockquote></details>

Copied from starknet_call, I have no idea, removed in both locations
___
*[`api/starknet_api_openrpc.json` line 449 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/4#-N3No2HvW-TM5BJq2TME-r1-449:-N3NoDOVAtg8MOFS3kDy:b2zwx7l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e6275ae34a94aa5c280eb41d5adf533c11588422/api/starknet_api_openrpc.json#L449)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so the state assumed is the state at the beginning or end of the block?
</blockquote></details>

End, like in other methods like call.


<!-- Sent from Reviewable.io -->

2022-05-31 07:17 UTC, lior-stark reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 449 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/4#-N3No2HvW-TM5BJq2TME-r1-449:-N3NyHTS4P6vrdwYh6HG:bivp1g8) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e6275ae34a94aa5c280eb41d5adf533c11588422/api/starknet_api_openrpc.json#L449)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

End, like in other methods like call.
</blockquote></details>

I'm not sure we were explicit about this there as well.
we should probably document it somewhere. here?


<!-- Sent from Reviewable.io -->

2022-05-31 07:23 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 449 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/4#-N3No2HvW-TM5BJq2TME-r1-449:-N3NzK9A21lrBdYBLKLK:b-7bwp2e) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e6275ae34a94aa5c280eb41d5adf533c11588422/api/starknet_api_openrpc.json#L449)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I'm not sure we were explicit about this there as well.
we should probably document it somewhere. here?
</blockquote></details>

Beginning makes no sense imo, part of the block header is "global_state_root", each block is associated with a state.


<!-- Sent from Reviewable.io -->

2022-05-31 11:49 UTC, lior-stark approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/4#-:-N3OwqHU1HN96rlPFK8q:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)



<!-- Sent from Reviewable.io -->

2022-05-31 14:36 UTC, ArielElp reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2022-05-31 14:36 UTC, merged