87 autogeneration
starkware-libs/starknet-specs pull request #88
Opened 2023-05-04 16:32 UTC by notV4l

- fix validation error on starknet_write_api
- fix issues for generating typings for starknet_write_api

- do not fix issues for generating typings for starknet_trace_api :
i suspect oneOf / allOf to create infinite loop while generating typings

2023-05-04 16:42 UTC, notV4l commented
for starknet_trace_api : 

- add  ADDRESS def to components/schema
```
 "ADDRESS": {
                "$ref": "./api/starknet_api_openrpc.json#/components/schemas/ADDRESS"
   }
```

- yarn gen_trace_api

--> infinite loop :(

2023-05-16 10:24 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/88)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @notV4l)

___
*[`api/starknet_write_api.json` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/88#-NVZ4cUAA3619fHu0fgt:-NVZ4cUAA3619fHu0fgu:b-plspii) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/443c47f4e75d0a1cf480729bb65aa9071c8439e1/api/starknet_write_api.json#L145)):*
> ```JSON
>                 "$ref": "./api/starknet_api_openrpc.json#/components/schemas/FUNCTION_CALL"
>             },
>             "SIERRA_ENTRY_POINT": {
> ```

why do we need all the new references in the write API?


<!-- Sent from Reviewable.io -->

2023-05-16 10:54 UTC, notV4l commented
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/88)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @notV4l)
> 
> _[`api/starknet_write_api.json` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/88#-NVZ4cUAA3619fHu0fgt:-NVZ4cUAA3619fHu0fgu:b-plspii) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/443c47f4e75d0a1cf480729bb65aa9071c8439e1/api/starknet_write_api.json#L145)):_
> 
> > ```json
> >                 "$ref": "./api/starknet_api_openrpc.json#/components/schemas/FUNCTION_CALL"
> >             },
> >             "SIERRA_ENTRY_POINT": {
> > ```
> 
> why do we need all the new references in the write API?

i was not able to validate schema / generate typings without this changes

> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/88)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @notV4l)
> 
> _[`api/starknet_write_api.json` line 145 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/88#-NVZ4cUAA3619fHu0fgt:-NVZ4cUAA3619fHu0fgu:b-plspii) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/443c47f4e75d0a1cf480729bb65aa9071c8439e1/api/starknet_write_api.json#L145)):_
> 
> > ```json
> >                 "$ref": "./api/starknet_api_openrpc.json#/components/schemas/FUNCTION_CALL"
> >             },
> >             "SIERRA_ENTRY_POINT": {
> > ```
> 
> why do we need all the new references in the write API?

i was not able to validate / generate types files without this changes

2023-07-31 07:09 UTC, tabaktoni commented
>   i suspect oneOf / allOf to create infinite loop while generating typings

Infinite loop is from recursive reference: FUNCTION_INVOCATION -> calls -> NESTED_CALL -> FUNCTION_INVOCATION ...
I don't know why it can't handle it, but there is an open issue with generator page.

2025-09-17 13:09 UTC, closed without merging